[workspace]
members = [ "crates/*" ]

[workspace.package]
edition = "2024"
version = "0.1.0"
authors = ["Bitwarden Inc"]
license = "AGPL-3.0"
keywords = ["akd", "key transparency"]


[workspace.dependencies]
akd-watch-auditor = { path = "crates/auditor" }
akd-watch-watcher = { path = "crates/watcher" }
akd-watch-web = { path = "crates/web" }
akd-watch-common = { path = "crates/common" }
thiserror = "2.0.12"

[workspace.lints.clippy]
unused_async = "deny"
unwrap_used = "deny"
