[package]
name = "akd-watch"
version = "0.1.0"
edition = "2024"

[dependencies]
akd = "0.11.0"
tokio = { version = "1", features = ["full"] }
axum = {version = "0.7", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
azure_storage = "0.17"
azure_storage_blobs = "0.17"
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "1.0"
