[package]
name = "akd_watch_auditor"

version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
tokio = { workspace = true}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = {workspace = true}
config = { workspace = true }
azure_storage = "0.17"
azure_storage_blobs = "0.17"
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "1.0"
akd_watch_common = { workspace = true }
akd = {workspace = true}
akd_core = {workspace = true}
futures-util = "0.3.31"
anyhow = "1.0.98"
ed25519-dalek = "2.2.0"
rand = "0.9.1"
